name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y make gcc g++ libssl-dev pkg-config wget
    - name: Run clippy
      run: cargo clippy
    - name: Build skycrane
      run: cargo build
    - name: Run tests
      run: cargo test
