name: Rust
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Clone Skyforge repo and copy wit API
      run: |
        git clone https://github.com/cloudflavor/skyforge.git 
        rm wit || true && ln -s skyforge/spec/wit
    - name: Run clippy
      run: cargo clippy
    - name: Build skycrane
      run: cargo build
    - name: Run tests
      run: cargo test
