name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  SKYCRANE_ASSETS_PATH: assets

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y make gcc g++ libssl-dev pkg-config
    - name: Install wasm32
      run: rustup target add wasm32-unknown-unknown
    - name: Build skycrane
      run: make build
    - name: Run tests
      run: make test
